### ISSUE TITLE
Error při vyhození Enchant věcí - 1.17

### ISSUE THREAD

**Issue by rejdo9544** [GameHausServer/GameHaus#10]
Pří vyhození Enchantovaných věcí (nether, herobrine, rankupy apod.) vyskočí error a daný předmět zmizí, hráč ho nevidí, ale jde sebrat. 
Parameters:
net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@4cd89bb4[
a=280011
b=[net.minecraft.network.syncher.DataWatcher$Item@3c30d60, net.minecraft.network.syncher.DataWatcher$Item@5a2b8f46, net.minecraft.network.syncher.DataWatcher$Item@68af91b3, net.minecraft.network.syncher.DataWatcher$Item@120fd432, net.minecraft.network.syncher.DataWatcher$Item@9bc631e, net.minecraft.network.syncher.DataWatcher$Item@feb9cd0, net.minecraft.network.syncher.DataWatcher$Item@1bdda697, net.minecraft.network.syncher.DataWatcher$Item@779f5f9a, net.minecraft.network.syncher.DataWatcher$Item@1d5166e4]
]
Error vždy jiné čísla/písmena.
A nebo při vyhození se neukáže nic a předmět přesto zmizí.

**Comment by hintik-dev** [comment]
Problém způsoboval plugin HolographicExtension. Byla nahrána upravená verze tohoto pluginu od neznámého autora.
