### ISSUE TITLE
Nelze uplatnit Vévoda RankUp

### ISSUE THREAD

**Issue by rejdo9544** [GameHausServer/GameHaus#3]
U RankUpu Vévoda, který může použít pouze Hrabě, to napsalo hráčovi **Tento kupon nelze s ohledem na aktuální hodnost použít**.

**Comment by hintik-dev** [comment]
Obdobný problém předpokládám bude i u rankupu na Hrabě, který může použít pouze panoš. Problém nastal při přechodu na LuckPerms. Nyní musíme vymyslet novou funkční strategii oprávnění, aby bylo možné problém vyřešit.

**Comment by rejdo9544** [comment]
Pro upřesnění. Jedná se RankUpy pro skupinu Hrabě/Vévoda. Klasické Ranky (z beden) fungují normálně.
Navíc mám pocit, že Hrabě si vycraftí Hrabě RankUp.

**Comment by rejdo9544** [comment]
Pro informaci: toto se děje jen pro skupiny Panoš/Hrabě. Klasické ranky (z beden) fungují normalně

**Comment by hintik-dev** [comment]
Problém byl vyřešen přidáním negativních permissích pro jednotlivé skupiny jednotlivým prémium skupinám.
