### ISSUE TITLE
Craft Hrabě RankUpu

### ISSUE THREAD

**Issue by rejdo9544** [GameHausServer/GameHaus#4]
Hrábě může vycraftit **Hrabě RankUp pro panoše**. Měl by to být Vévoda RankUp.

**Comment by hintik-dev** [comment]
Problém bude způsoben změnou systému na oprávnění (LuckPerms). Pravděpodobně problém bude vyřešen vyřešením exkluzivních oprávněních pro jednotlivé skupiny.

**Comment by hintik-dev** [comment]
Problém byl vyřešen přidáním negativních permissích pro jednotlivé skupiny jednotlivým prémium skupinám.
